version: "3.8"

services:
  iac:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
    working_dir: "/usr/src"
    # ports:
    #   - "8080:8080"
    tty: true
